name: CI

on: [ push, pull_request ]

jobs:

  java-17:

    name: Java 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: git fetch --prune --unshallow --tags

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Test
        run: ./gradlew build
