name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * Mon"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: request-token
        uses: permissionizer/request-token@v1
        with:
          target-repository: ${{ github.repository }}
          permissions: |
            contents: write
            pull-requests: write

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: '${{ steps.request-token.outputs.token }}'
          merge-method: SQUASH
          reviewers: gavlyukovskiy
